### ISSUE TITLE
Useconsole.log type error

### ISSUE THREAD

**Issue by gavinisagi** [psq/stacks-dump#15]
https://github.com/psq/stacks-dump/blob/d9ae8420f61c68019c8eeb24678dcff77216524c/report.js#L597
Following works for me.
```
!use_csv && console.log("pox invalid", row.block_height, row.burn_header_hash, parent && parent.parent_burn_header_hash)
```

**Comment by psq** [comment]
this was fixed in c42a6f7f9c6388dd26b3375a1f92e48e4d15d812
