### ISSUE TITLE
Add control to output

### ISSUE THREAD

**Issue by whoabuddy** [psq/stacks-dump#17]
Right now when running stacks-dump, the result is block data, miner statistics, and total statistics.

This is all great information, but the block data takes up 90% of the output, and may not be immediately useful to someone running the report for the statistics at the end. [This online version](https://friedger.github.io/pub-stacks-dump/) from @friedger is a little bogged down by it.

It would be nice if we could quiet the output, either by default or by option, and add on additional items as needed.

It would also be nice to be able to target individual outputs for further integration into future tools. (i.e. I only want the block data, and I'm using that to do *this*).

## Option 1 - Quiet output

Add an option `-q, --quiet` that only outputs the miner statistics (and maybe final stats).

## Option 2 - Change output structure

Make it so that the default is only one thing (miner statistics?), and add:

| Switch | Description |
| --- | --- |
| `-b, --blocks` | output block data |
| `-t, --totals` | add final statistics |

I'm open to doing it either way, and would like some guidance so we can make sure this gets included upstream :slightly_smiling_face: 

The options are expanding quickly!!

**Comment by psq** [comment]
I'd rather have negative options to remove output from the default, so something like:

`-b`, `--no-blocks`
`-g`, `--no-totals` (`-t` is used for displaying transactions)
