### ISSUE TITLE
SqliteError: database is locked

### ISSUE THREAD

**Issue by friedger** [psq/stacks-dump#21]
I received this error.

file:///home/ubuntu/stacks-dump/report.js:537
const stmt_all_payments = headers_db.prepare('SELECT * FROM payments')
                                     ^
SqliteError: database is locked
    at file:///home/ubuntu/stacks-dump/report.js:537:38

Maybe related to https://github.com/blockstack/stacks-blockchain/issues/2334

**Comment by friedger** [comment]
The node is still syncing.

**Comment by psq** [comment]
not sure I can do much, only opening as read-only.

**Comment by friedger** [comment]
I think this happens if the script is called again while it is still running.
