### ISSUE TITLE
Only use canonical blocks for last block info

### ISSUE THREAD

**Issue by friedger** [psq/stacks-dump#23]
Sometimes the report takes blocks as the last block that are not yet confirmed, resulting in zero block rewards like below:

![Screenshot from 2021-01-29 17-46-19](https://user-images.githubusercontent.com/1449049/106303041-f8c1e480-6259-11eb-82db-abd92d3e0779.png)

![Screenshot from 2021-01-29 17-46-30](https://user-images.githubusercontent.com/1449049/106303022-f495c700-6259-11eb-92aa-b6d669afea3e.png)

**Comment by psq** [comment]
won't fix, but would consider a PR
