### ISSUE TITLE
Script ready for Xenon?

### ISSUE THREAD

**Issue by JonasPf** [psq/stacks-dump#3]
Is this script ready for Xenon? I tried but couldn't get it working and the name (`report-pox-krypton.js`) suggests otherwise.

Here is what I did:

First I ran into problems where it couldn't find some files. The following changes seems to fix that:

```
-const burnchain_db_path = 'burnchain/db/bitcoin/regtest/burnchain.db'
+const burnchain_db_path = 'burnchain/db/bitcoin/testnet/burnchain.db'
-const sortition_db_path = "burnchain/db/bitcoin/regtest/sortition.db/marf"
+const sortition_db_path = "burnchain/db/bitcoin/testnet/sortition.db/marf"
```

After these changes I got the following error:

```
sudo node report-pox-krypton.js /data/stacks/
========================================================================================================================
Leader key registrations
1894317 43 ST2X2FYCY01Y7YR2TGC2Y6661NFF3SMH0NGXPWTV5
file:///home/enode/stacks-dump/report-pox-krypton.js:630
      op.LeaderBlockCommit.public_key = secp256k1.publicKeyConvert(Buffer.from(op.LeaderBlockCommit.input.public_keys[0].key, 'hex'), op.LeaderBlockCommit.input.public_keys[0].compressed).toString('hex')
                                                                                                                     ^

TypeError: Cannot read property '0' of undefined
    at process_burnchain_ops (file:///home/enode/stacks-dump/report-pox-krypton.js:630:118)
    at file:///home/enode/stacks-dump/report-pox-krypton.js:647:3
    at file:///home/enode/stacks-dump/report-pox-krypton.js:783:3
    at ModuleJob.run (node:internal/modules/esm/module_job:152:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**Comment by psq** [comment]
thanks for the details.  @tyGavinZJU already mentioned that the leader block commit json was different.  Will take a look shortly.

**Comment by psq** [comment]
addressed with b0b9b7facbc483635cb6c998f18e70e3a9641d37 and adding a file for xenon (some day, it will detect automatically...)

**Comment by gavinisagi** [comment]
> thanks for the details. @tyGavinZJU already mentioned that the leader block commit json was different. Will take a look shortly.

I am maintaining [Mining-Monitor](https://github.com/Daemon-Technologies/Mining-Monitor) recently. Will help to solve issues in this repo in the near future. 

I wonder if stacks-dump will be abandoned if we have bitcoind in Xenon. Does it cover all the message of stacks db? What do you think @psq?

**Comment by psq** [comment]
stacks-dump will still make sense for mainnet, and more could be added.  Initially, I started to help keep track of the forks, which are still being created too often and we'll need to fix that one way or an other so it rarely happens when no miner have malicious intent.
