### ISSUE TITLE
transaction report crashes

### ISSUE THREAD

**Issue by joshmatix** [psq/stacks-dump#4]
node report  /tmp/stacks-testnet-2e5a041657aeb587  - **works fine.**

 node report -t /tmp/stacks-testnet-2e5a041657aeb587

file:///home/tom/stacks-dump/report.js:387
const stmt_all_transactions = use_txs ? headers_db.prepare('SELECT * FROM transactions') : null
                                                   ^
**SqliteError: no such table: transactions**
    at file:///home/tom/stacks-dump/report.js:387:52
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

**Comment by psq** [comment]
stacks-node needs to be built with `cargo build --workspace --features tx_log --bin stacks-node` as explained in the readme
