### ISSUE TITLE
regular report - property 'payments' of undefined

### ISSUE THREAD

**Issue by joshmatix** [psq/stacks-dump#5]
pox invalid 361 55deecdea89178421dbf0e8a0fa16ea20d5d3540aeb43f1acf9505a6c8b40fe4 55deecdea89178421dbf0e8a0fa16ea20d5d3540aeb43f1acf9505a6c8b40fe4
(node:7166) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'payments' of undefined
    at process_payments (file:///home/tom/stacks-dump/report.js:555:55)
    at file:///home/tom/stacks-dump/report.js:685:3
    at file:///home/tom/stacks-dump/report.js:830:3
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7166) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by psq** [comment]
I'll need a zip of the data folder so I can debug this.
