### ISSUE TITLE
Staging DB not found

### ISSUE THREAD

**Issue by friedger** [psq/stacks-dump#6]
Running with krypton on commit 1a34c15684419eca3b8234394c8aca186f7568ad:

```
node report ~/data/stacks-krypton/

/home/friedger/_repos/github/psq/stacks-dump/node_modules/better-sqlite3/lib/database.js:34
	return new CPPDatabase(filename, filenameGiven, anonymous, readonly, fileMustExist, timeout, verbose || null);
	       ^
SqliteError: unable to open database file
    at new Database (/home/friedger/_repos/github/psq/stacks-dump/node_modules/better-sqlite3/lib/database.js:34:9)
    at file:///home/friedger/_repos/github/psq/stacks-dump/report.js:365:20
    at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

```

There is not file `staging.db` in the directory.

**Comment by psq** [comment]
looks to be gone now with the latest merge from next.  Will need to figure out where the tables are.  This reorg had been coming

**Comment by psq** [comment]
just to clarify, the version to use with krypton, before the last major merge from next should still have a staging.db file, and this should only apply to xenon.  For example, v24.0.0.0-xenon does have a staging.db file

**Comment by friedger** [comment]
I would drop support for 24.0 ;-P

**Comment by psq** [comment]
unless the contest drops it, I need to keep supporting it for a bit longer

**Comment by friedger** [comment]
Hopefully, they make a wise decision: https://github.com/Daemon-Technologies/docs/issues/25
